name: FoundBiome
main: net.nucloid.foundbiome.FoundBiome
version: 0.1
author: Nucloid
description: Allows players to see when they change biomes, and what biomes they have visited.

commands:
    fb:
        description: Master command for FoundBiome