name: FoundBiome
main: net.alureon.foundbiome.FoundBiome
version: 0.9
author: alureon
description: Allows players to see when they change biomes, and what biomes they have visited.

commands:
    fb:
        description: Master command for FoundBiome